@startuml
    Title <size:20>\nPattern: Strategy\n

    interface ComparatorInterface {
        + compare(): int;
    }

    class Context {
        - comparator;
        + __construct(ComparatorInterface)
        + executeStrategy()
    }

    class DateComparator implements ComparatorInterface {
        + compare(): int
    }

    class IdComparator implements ComparatorInterface {
        + compare(): int
    }

	ComparatorInterface -left-> Context: injects
@enduml