@startuml
    Title <size:20>\nPattern: Proxy\n

    interface BankAccount {
        + deposit()
        + getBalance(): int
    }

    class HeavyBankAccount implements BankAccount {
        - transactions: array
        + deposit()
        + getBalance(): int
    }

    package Proxy <<Rectangle>> {
        class BankAccountProxy implements BankAccount {
            - balance
            __construct(BankAccount)
            + getBalance(): int
        }
    }

    BankAccountProxy <-- HeavyBankAccount: " injects"
@enduml





