@startuml
    Title <size:20>\nPattern: Pool\n

	class WorkerPool implements Countable {
		- $occupiedWorkers = []
		- $freeWorkers = []
		+ get()
		+ dispose(StringReverseWorker)
		+ count()
	}

	class StringReverseWorker {
		- $createdAt
		+  __construct()
		+ run()
	}

	StringReverseWorker -left-> WorkerPool: " injects"

@enduml