@startuml
    Title <size:20>\nPattern: Pool\n

	class WorkerPool implements Countable {
		- $occupiedWorkers = []
		- $freeWorkers = []
		+ get(): Workers
		+ dispose(StringReverseWorker): void
		+ count(): int
	}

	class StringReverseWorker {
		- $createdAt
		+  __construct()
		+ run(): string
	}

	StringReverseWorker -left-> WorkerPool: " injects"

@enduml