@startuml
	Title <size:20>\nPattern: Visitor\n

    interface Role {
        + accept(RoleVisitorInterface): void
    }

    class Group implements Role {
        - name
        + __construct()
        + getName(): string
        + accept(RoleVisitorInterface): void
    }

    class User implements Role {
        - name
        + __construct()
        + getName(): string
        + accept(RoleVisitorInterface): void
    }

    interface RoleVisitorInterface {
        + visitUser(User): void
        + visitGroup(Group): void
    }

    class RoleVisitor implements RoleVisitorInterface{
        - visited: array
        + visitGroup(Group): void
        + visitUser(User): void
        + getVisited(): array
    }

    RoleVisitorInterface -left-> Group: " injects"
    RoleVisitorInterface -right-> User: " injects"
@enduml