@startuml
	Title <size:20>\nPattern: Visitor\n

    interface Role {
        + accept(RoleVisitorInterface);
    }

    interface RoleVisitorInterface {
        + visitUser(User);
        + visitGroup(Group);
    }

    class Group implements Role {
        - name
        + __construct()
        + getName(): string
        + accept(RoleVisitorInterface)
    }

    class User implements Role {
        - name
        + __construct()
        + getName(): string
        + accept(RoleVisitorInterface)
    }

    class RoleVisitor implements RoleVisitorInterface{
        - visited: array
        + visitGroup(Group)
        + visitUser(User)
        + getVisited(): array
    }

    RoleVisitorInterface -left-> Group: " injects"
    RoleVisitorInterface -right-> User: " injects"
@enduml