@startuml
    Title <size:20>\nPattern: Mediator\n

    interface ChatRoomMediator{
        + showMessage(User, string): string;
    }

    class ChatRoom implements ChatRoomMediator {
        + showMessage(User): string
    }

    class User {
        * name;
        * chatMediator;
        + __construct(ChatRoomMediator)
        + getName()
        + send()
    }

    ChatRoomMediator -left-> User: Injects


@enduml