@startuml
    Title <size:20>\nPattern: Command\n

    interface Command {
        + execute(): void
        + undo(): void
        + redo(): void
    }

    class Bulb {
        + turnOn(): string
        + turnOff(): string
    }

    class TurnOn implements Command {
        - $bulb
        + __construct(Bulb)
        + execute(): void
        + undo(): void
        + redo(): void
    }

    class TurnOff implements Command {
        - $bulb
        + __construct(Bulb)
        + execute(): void
        + undo(): void
        + redo(): void
    }

    class RemoteControl {
        + submit(Command): void
    }

    Bulb -left-> TurnOn: " injects"
    Bulb -right-> TurnOff: " injects"
    Command -left-> RemoteControl: " injects"
@enduml