@startuml
    Title <size:20>\nPattern: Command\n

    interface Command {
        + execute();
        + undo();
        + redo();
    }

    class Bulb {
        + turnOn()
        + turnOff()
    }

    class TurnOn implements Command {
        protected $bulb;
        + __construct(Bulb)
        + execute()
        + undo()
        + redo()
    }

    class TurnOff implements Command {
        protected $bulb;
        + __construct(Bulb)
        + execute()
        + undo()
        + redo()
    }

    class RemoteControl {
        + submit(Command)
    }

    Bulb -left-> TurnOn: " injects"
    Bulb -right-> TurnOff: " injects"
    Command -left-> RemoteControl: " injects"
@enduml