@startuml
    Title <size:20>\nPattern: Flyweight\n

    class GreenTea {
    	- type
    	__construct(type)
    	+ getType()

    }

    class TeaFactory {
        * availableTea: array
        + make(): GreenTea
        + getAvailableTea()
    }

    class TeaShop {
        * orders
        * teaMaker
        + __construct(TeaFactory)
        + takeOrder()
        + serve(): array
    }

    GreenTea --> TeaFactory: " injects"
    TeaFactory --> TeaShop: " injects"
@enduml