@startuml
    Title <size:20>\nPattern: Flyweight\n

    class GreenTea {
    	- type
    	__construct()
    	+ getType(): string
    }

    class TeaFactory {
        * availableTea: array
        + make(): GreenTea
        + getAvailableTea(): array
    }

    class TeaShop {
        * orders: array
        * teaMaker: TeaFactory
        * messages: array
        + __construct(TeaFactory)
        + takeOrder(): void
        + serve(): array
    }

    GreenTea -left-> TeaFactory: " injects"
    TeaFactory -left-> TeaShop: " injects"
@enduml