@startuml
    Title <size:20>\nPattern: Flyweight\n

    interface Flyweight {
        + render(): string
    }

    class CharacterFlyweight implements Flyweight {
        - name: string
        + __construct()
        + render(): string
    }

    class FlyweightFactory implements Countable {
        - pool: array
        + get(): CharacterFlyweight
        + count(): int
    }

    CharacterFlyweight -left-> FlyweightFactory: " injects"
@enduml
