@startuml
    Title <size:20>\nPattern: Flyweight\n

    interface Flyweight {
        + render(): string
    }

    interface Countable

    class CharacterFlyweight {
        - name: string
        + __construct()
        + render(): string
    }

    class FlyweightFactory {
        - pool: array
        + get(): CharacterFlyweight
        + count(): int
    }

    CharacterFlyweight --> FlyweightFactory: " injects"
    CharacterFlyweight .left.|> Flyweight: " implements"
    FlyweightFactory .left.|> Countable: " implements"
@enduml
