@startuml
    Title <size:20>\nPattern: Proxy\n

    interface Door {
        + open(): string
        + close(): string
    }

    class LabDoor implements Door {
        + open(): string
        + close(): string
    }

    class SecuredDoor {
    	* door
    	+ __construct(Door)
        + open(): string
        + close(): string
        + authenticate(): bool
    }

	LabDoor -right-> SecuredDoor: " injects"
@enduml