@startuml
    Title <size:20>\nPattern: NullObject\n

    interface Logger {
		+ log()
	}

    class NullLogger {
		+ log()
	}

    class PrintLogger {
		+ log()
    }

	class Service {
		- $logger
		+ __construct(Logger $logger)
		+ log()
	}

    NullLogger ..|> Logger: " implements"
    PrintLogger ..|> Logger: " implements"
    Logger --> Service: " injects"
@enduml