@startuml
    Title <size:20>\nPattern: NullObject\n

    interface Logger {
		+ log()
	}

    class NullLogger implements Logger {
		+ log()
	}

    class PrintLogger implements Logger {
		+ log()
    }

	class Service {
		- $logger
		+ __construct(Logger $logger)
		+ log()
	}

    Logger -left-> Service: " injects"
@enduml