@startuml
	Title <size:20>\nPattern: Visitor\n

    interface Animal {
        + accept(AnimalOperation): string
    }

    class Dolphin implements Animal {
        + speak(): string
        + accept(AnimalOperation): string
    }

    class Lion implements Animal {
        + roar(): string
        + accept(AnimalOperation): string
    }

    class Monkey implements Animal {
        + shout(): string
        + accept(AnimalOperation): string
    }

    interface AnimalOperation {
        + visitMonkey(Monkey): string
        + visitLion(Lion): string
        + visitDolphin(Dolphin): string
    }

    class Jump implements AnimalOperation {
        + visitMonkey(Monkey): string
        + visitLion(Lion): string
        + visitDolphin(Dolphin): string
    }

    class Speak implements AnimalOperation {
        + visitMonkey(Monkey): string
        + visitLion(Lion): string
        + visitDolphin(Dolphin): string
    }

    AnimalOperation -left-> Animal: " injects"
@enduml