@startuml
	Title <size:20>\nPattern: Visitor\n

    interface Animal {
        + accept(AnimalOperation)
    }

    interface AnimalOperation {
        + visitMonkey(Monkey)
        + visitLion(Lion)
        + visitDolphin(Dolphin)
    }

    class Dolphin implements Animal {
        + speak()
        + accept(AnimalOperation)
    }

    class Lion implements Animal {
        + roar()
        + accept(AnimalOperation)
    }

    class Monkey implements Animal {
        + shout()
        + accept(AnimalOperation)
    }

    class Jump implements AnimalOperation {
        + visitMonkey(Monkey)
        + visitLion(Lion)
        + visitDolphin(Dolphin)
    }

    class Speak implements AnimalOperation {
        + visitMonkey(Monkey)
        + visitLion(Lion)
        + visitDolphin(Dolphin)
    }

    AnimalOperation -left-> Animal: " injects"
@enduml