@startuml
    Title <size:20>\nPattern: Facade\n

    package Facade <<Rectangle>> {
        class ComputerFacade {
            * computer
            + __construct(Computer)
            + turnOn(): string
            + turnOff(): string
        }
    }

    class Computer {
        + getElectricShock(): string
        + makeSound(): string
        + showLoadingScreen(): string
        + bam(): string
        + closeEverything(): string
        + sooth(): string
        + pullCurrent(): string
    }

    Computer -right-> ComputerFacade: injects
@enduml