@startuml
	Title <size:20>\nPattern: Observer\n

	class User implements SplSubject {
		- email
		- observers
		+ __construct(SplObjectStorage)
		+ attach(SplObserver)
		+ detach(SplObserver)
		+ changeEmail()
		+ notify()
	}

	class UserObserver implements SplObserver {
		- changedUsers: array
		+ update(SplSubject)
		+ getChangedUsers(): array
	}

	User -left-> UserObserver: " injects"
	SplObjectStorage -left-> User: " injects"
@enduml