@startuml
	Title <size:20>\nPattern: Observer\n

	class User implements SplSubject {
		- email: string
		- observers: array
		+ __construct(SplObjectStorage)
		+ attach(SplObserver): void
		+ detach(SplObserver): void
		+ changeEmail(): void
		+ notify(): void
	}

	class UserObserver implements SplObserver {
		- changedUsers: array
		+ update(SplSubject): void
		+ getChangedUsers(): array
	}

	User -left-> UserObserver: " injects"
	SplObjectStorage -left-> User: " injects"
@enduml