@startuml
    Title <size:20>\nPattern: Mediator\n

    interface MediatorInterface {
        + sendResponse($content): string;
        + makeRequest(): string;
        + queryDb(): string;
    }

    abstract class Colleague {
        * $mediator;
        + setMediator(MediatorInterface)
    }

    class Mediator implements MediatorInterface {
        - server
        - database
        - client
        + __construct(Database, Client, Server)
        + makeRequest(): string
        + queryDb(): string
        + sendResponse(): string
    }

	class Client extends Colleague {
		+ request(): string
		+ output(): string
	}

	class Database extends Colleague {
		+ getData(): string
	}

	class Server extends Colleague {
		+ process(): string
	}

	MediatorInterface -left-> Colleague: injects

@enduml