@startuml
	Title <size:20>\nPattern: Observer\n

	class JobPost {
		- title;
		+ __construct()
		+ getTitle(): string
	}

	class JobSeeker {
		- name;
		+ __construct()
		+ onJobPosted(JobPost): string
	}

	class EmploymentAgency {
		- observers: array
		protected function notify(JobPost $jobPosting): array
		+ attach($observer): void
		+ addJob(JobPost $jobPosting): array
		+ getObservers(): array
	}

	JobPost -right-> JobSeeker: injects
	JobPost -left-> EmploymentAgency: injects




@enduml